stages:
  - lint
  - typecheck
  - deploy-prod

include:
  - component: $CI_SERVER_FQDN/cloudflare/ci/pnpm/run@~latest
    inputs:
      runOnMR: true
      runOnBranches: ^main$
      stage: lint
      jobPrefix: lint
      PNPM_RUN_TARGET: 'check'
  - component: $CI_SERVER_FQDN/cloudflare/ci/pnpm/run@~latest
    inputs:
      runOnMR: true
      runOnBranches: ^main$
      stage: typecheck
      jobPrefix: typecheck
      PNPM_RUN_TARGET: 'cf-typegen'
  - component: $CI_SERVER_FQDN/cloudflare/ci/pnpm/run@~latest
    inputs:
      runOnBranches: main
      stage: deploy-prod
      jobPrefix: deploy-prod
      PNPM_RUN_TARGET: 'deploy'

lint-run:
  timeout: 10 minutes
  stage: lint

typecheck-run:
  timeout: 10 minutes
  stage: typecheck

deploy-prod-run:
  timeout: 15 minutes
  stage: deploy-prod
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
